# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nancy < Formula
  desc "A tool to check for vulnerabilities in your Golang dependencies, powered by Sonatype OSS Index"
  homepage "https://github.com/sonatype-nexus-community/nancy"
  version "1.0.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.7/nancy-v1.0.7-darwin-amd64.tar.gz"
    sha256 "3db487381f75931a0c5486bc45d69e3e62b98ecb34b1288d7e7a8b9086a68efc"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.7/nancy-v1.0.7-linux-amd64.tar.gz"
    sha256 "6676fa9f3ba6a5d0a7f3373194fa7eb46fba928f99ca971e7a9229e8806053b7"
  end

  def install
    bin.install "nancy"
  end
end
