# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nancy < Formula
  desc "A tool to check for vulnerabilities in your Golang dependencies, powered by Sonatype OSS Index"
  homepage "https://github.com/sonatype-nexus-community/nancy"
  version "1.0.17"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.17/nancy-v1.0.17-darwin-amd64.tar.gz"
    sha256 "87b109d8172fc5cac83ec92fae449b4cd9bc63a06ccd3a738b1853dc5d269d91"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.17/nancy-v1.0.17-linux-amd64.tar.gz"
    sha256 "91ad2c7fa3d6d775c59b5c7e7f59d16c6de0fda95ffdc4c539b2ce201e0ce433"
  end

  def install
    bin.install "nancy"
  end
end
